# Topics/services exposed by the Tello driver
robot:
  battery_topic:   /tello/battery
  cmd_vel_topic:   /tello/cmd_vel
  image_topic:     /tello/camera/image_raw/compressed

bt:
  name: tello_bt          # behaviour‑tree file (see robot_bt/bt/)
  battery_low_threshold: 0.25
